### PR TITLE
106 table 09 gt@main

### LINKED ISSUE #106: Create `make_table_09_gtsum`
Create function `make_table_09_gtsum` to build table 9 using the `gt` and `gtsummary` packages. 

See https://github.com/pharmaverse/falcon/issues/3 and https://pharmaverse.github.io/falcon/quarto/table-templates/template-table_09.html for specifications for this table. The table output should be very similar to the output created by `make_table_09`.

Once this function is created it can be added to the Table 9 template page on the falcon site.

Similar to https://github.com/pharmaverse/falcon/issues/99.

### PR DESCRIPTION
**Pull request by mattkorb**
# Pull Request

Closes #106

### CODE REVIEW

**Comment by mattkorb** [comment]
I know that the files for the webpage still need to be updated. I just wanted to already create th PR so that someone reviews the code.

**Comment by ayogasekaram** [comment]
hey @mattkorb! Looking great so far. I pushed a few changes after merging the updates from main into the branch. It looks like a couple of the checks are failing (like lintr). Would you be able to resolve those in the mean time? I'll take a look at it again afterwards. Thanks!

**Comment by mattkorb** [comment]
hey @ayogasekaram thank you for the review :)
I will take a look at the failing checks and will let you know once they are resolved.

**Review by ayogasekaram — APPROVED** [review]
lgtm @mattkorb!

**Pull request merged**
