### PR TITLE
105 table 09 tplyr

### LINKED ISSUE #105: Create `make_table_09_tplyr`
Create function `make_table_09_tplyr` to build table 9 using the `tplyr` and `tfrmt` packages. 

See https://github.com/pharmaverse/falcon/issues/3 and https://pharmaverse.github.io/falcon/quarto/table-templates/template-table_09.html for specifications for this table. The table output should be very similar to the output created by `make_table_09`.

Once this function is created it can be added to the Table 9 template page on the falcon site.

Similar to https://github.com/pharmaverse/falcon/issues/100.

### PR DESCRIPTION
**Pull request by jknizia**
# Pull Request

Closes #105

### CODE REVIEW

**Review by ayogasekaram — CHANGES_REQUESTED** [review]
Hi @jknizia! Thank you so much for working on this. I think the code looks great but may be a modification to the table layers. When running the tplyr function, the Reported term seems to come before the system organ class - I think according to the spec it should be the other way around.

image

**Comment by jknizia** [comment]
> Hi @jknizia! Thank you so much for working on this. I think the code looks great but may be a modification to the table layers. When running the tplyr function, the Reported term seems to come before the system organ class - I think according to the spec it should be the other way around.
> 
> image

Hi @ayogasekaram, thank you so much for catching this! I'll have a look at it next week.

**Comment by ayogasekaram** [comment]
Hi @jknizia Thank you so much for addressing the comments from the review. The changes look great but I think there may be a change in the processing that needs to be addressed. When I run the 2nd tplyr example (line 129) I get the error below:
image

Apart from this, the rest seems to work well. 
I'm good to merge after the error is corrected.

**Comment by jknizia** [comment]
> Hi @jknizia Thank you so much for addressing the comments from the review. The changes look great but I think there may be a change in the processing that needs to be addressed. When I run the 2nd tplyr example (line 129) I get the error below: image
> 
> Apart from this, the rest seems to work well. I'm good to merge after the error is corrected.

Hi @ayogasekaram, thanks for the hint. However, the example works fine at my end... Could you try again, please?

**Comment by mattkorb** [comment]
> > Hi @jknizia Thank you so much for addressing the comments from the review. The changes look great but I think there may be a change in the processing that needs to be addressed. When I run the 2nd tplyr example (line 129) I get the error below: image
> > Apart from this, the rest seems to work well. I'm good to merge after the error is corrected.
> 
> Hi @ayogasekaram, thanks for the hint. However, the example works fine at my end... Could you try again, please?

Hi @ayogasekaram and @jknizia , the example works for me as well.

**Comment by ayogasekaram** [comment]
> > > Hi @jknizia Thank you so much for addressing the comments from the review. The changes look great but I think there may be a change in the processing that needs to be addressed. When I run the 2nd tplyr example (line 129) I get the error below: image
> > > Apart from this, the rest seems to work well. I'm good to merge after the error is corrected.
> > 
> > 
> > Hi @ayogasekaram, thanks for the hint. However, the example works fine at my end... Could you try again, please?
> 
> Hi @ayogasekaram and @jknizia , the example works for me as well.

hey @jknizia! I was able to get Emily to pull this branch and run the test and she's getting the same `map()` error from the image above. We are using the latest version of {purrr} (1.0.2) - would you be able to update your version just to make sure it's not related to that? If it is, we may have to rework the function code and set a minimum package version in the description.

**Comment by jknizia** [comment]
> > > > Hi @jknizia Thank you so much for addressing the comments from the review. The changes look great but I think there may be a change in the processing that needs to be addressed. When I run the 2nd tplyr example (line 129) I get the error below: image
> > > > Apart from this, the rest seems to work well. I'm good to merge after the error is corrected.
> > > 
> > > 
> > > Hi @ayogasekaram, thanks for the hint. However, the example works fine at my end... Could you try again, please?
> > 
> > 
> > Hi @ayogasekaram and @jknizia , the example works for me as well.
> 
> hey @jknizia! I was able to get Emily to pull this branch and run the test and she's getting the same `map()` error from the image above. We are using the latest version of {purrr} (1.0.2) - would you be able to update your version just to make sure it's not related to that? If it is, we may have to rework the function code and set a minimum package version in the description.

Hi @ayogasekaram, even with {purrr} v1.0.2 it works fine for me... No error on my end: 
image

**Comment by jknizia** [comment]
The error arises only with {Tplyr} versions > 1.1.0. As a quick fix, we limit the {Tplyr} version for {falcon} to <= 1.0.0. This is only a temporary solution until we solved the issue for higher {Tplyr} versions.

**Comment by jknizia** [comment]
Dear @ayogasekaram, I have deactived the risk diff functionality for now, until the issue with {Tplyr} is solved.

**Pull request merged**
